// Generated by gencpp from file robotcraft2024_driver_g2/set_rgb.msg
// DO NOT EDIT!


#ifndef ROBOTCRAFT2024_DRIVER_G2_MESSAGE_SET_RGB_H
#define ROBOTCRAFT2024_DRIVER_G2_MESSAGE_SET_RGB_H

#include <ros/service_traits.h>


#include <robotcraft2024_driver_g2/set_rgbRequest.h>
#include <robotcraft2024_driver_g2/set_rgbResponse.h>


namespace robotcraft2024_driver_g2
{

struct set_rgb
{

typedef set_rgbRequest Request;
typedef set_rgbResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_rgb
} // namespace robotcraft2024_driver_g2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotcraft2024_driver_g2::set_rgb > {
  static const char* value()
  {
    return "57a090aa7c99ddb5bfd28162e649c952";
  }

  static const char* value(const ::robotcraft2024_driver_g2::set_rgb&) { return value(); }
};

template<>
struct DataType< ::robotcraft2024_driver_g2::set_rgb > {
  static const char* value()
  {
    return "robotcraft2024_driver_g2/set_rgb";
  }

  static const char* value(const ::robotcraft2024_driver_g2::set_rgb&) { return value(); }
};


// service_traits::MD5Sum< ::robotcraft2024_driver_g2::set_rgbRequest> should match
// service_traits::MD5Sum< ::robotcraft2024_driver_g2::set_rgb >
template<>
struct MD5Sum< ::robotcraft2024_driver_g2::set_rgbRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotcraft2024_driver_g2::set_rgb >::value();
  }
  static const char* value(const ::robotcraft2024_driver_g2::set_rgbRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotcraft2024_driver_g2::set_rgbRequest> should match
// service_traits::DataType< ::robotcraft2024_driver_g2::set_rgb >
template<>
struct DataType< ::robotcraft2024_driver_g2::set_rgbRequest>
{
  static const char* value()
  {
    return DataType< ::robotcraft2024_driver_g2::set_rgb >::value();
  }
  static const char* value(const ::robotcraft2024_driver_g2::set_rgbRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotcraft2024_driver_g2::set_rgbResponse> should match
// service_traits::MD5Sum< ::robotcraft2024_driver_g2::set_rgb >
template<>
struct MD5Sum< ::robotcraft2024_driver_g2::set_rgbResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotcraft2024_driver_g2::set_rgb >::value();
  }
  static const char* value(const ::robotcraft2024_driver_g2::set_rgbResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotcraft2024_driver_g2::set_rgbResponse> should match
// service_traits::DataType< ::robotcraft2024_driver_g2::set_rgb >
template<>
struct DataType< ::robotcraft2024_driver_g2::set_rgbResponse>
{
  static const char* value()
  {
    return DataType< ::robotcraft2024_driver_g2::set_rgb >::value();
  }
  static const char* value(const ::robotcraft2024_driver_g2::set_rgbResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTCRAFT2024_DRIVER_G2_MESSAGE_SET_RGB_H
