// Generated by gencpp from file robotcraft2024_driver_g2/set_rgbResponse.msg
// DO NOT EDIT!


#ifndef ROBOTCRAFT2024_DRIVER_G2_MESSAGE_SET_RGBRESPONSE_H
#define ROBOTCRAFT2024_DRIVER_G2_MESSAGE_SET_RGBRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotcraft2024_driver_g2
{
template <class ContainerAllocator>
struct set_rgbResponse_
{
  typedef set_rgbResponse_<ContainerAllocator> Type;

  set_rgbResponse_()
    : success(false)  {
    }
  set_rgbResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_rgbResponse_

typedef ::robotcraft2024_driver_g2::set_rgbResponse_<std::allocator<void> > set_rgbResponse;

typedef boost::shared_ptr< ::robotcraft2024_driver_g2::set_rgbResponse > set_rgbResponsePtr;
typedef boost::shared_ptr< ::robotcraft2024_driver_g2::set_rgbResponse const> set_rgbResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator1> & lhs, const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator1> & lhs, const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotcraft2024_driver_g2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotcraft2024_driver_g2/set_rgbResponse";
  }

  static const char* value(const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_rgbResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotcraft2024_driver_g2::set_rgbResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTCRAFT2024_DRIVER_G2_MESSAGE_SET_RGBRESPONSE_H
